# Generated by Django 4.0.3 on 2022-06-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BddFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(blank=True, null=True)),
                ('img_upload', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=4000)),
                ('taille_texte', models.PositiveIntegerField(blank=True, null=True)),
                ('fichier', models.FileField(default='', upload_to='fichiers/%Y/%m/%D')),
            ],
        ),
    ]
