# Generated by Django 4.0.3 on 2022-04-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=25)),
                ('subtitle', models.CharField(max_length=25)),
                ('piclink', models.CharField(max_length=25)),
            ],
        ),
    ]
