# Generated by Django 4.0.3 on 2022-06-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccueilIntroMun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url1', models.URLField(blank=True, null=True)),
                ('img_upload1', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('img_url2', models.URLField(blank=True, null=True)),
                ('img_upload2', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('img_url3', models.URLField(blank=True, null=True)),
                ('img_upload3', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('video_url', models.URLField()),
                ('titre', models.CharField(max_length=50)),
                ('taille_titre', models.PositiveIntegerField(blank=True, null=True)),
                ('texte', models.TextField(max_length=2000)),
                ('taille_texte', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
