# Generated by Django 4.0.3 on 2022-06-01 00:55

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_upload', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('color', colorfield.fields.ColorField(default='#5EFF93', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.EmailField(max_length=254)),
                ('address2', models.EmailField(max_length=254)),
                ('address3', models.EmailField(max_length=254)),
                ('couleur', colorfield.fields.ColorField(default='#55d6aa', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_de_la_Génération', models.CharField(default='', max_length=100)),
                ('Citation', models.TextField(default='toto', max_length=2000)),
                ('photo_de_groupe', models.ImageField(default='images/MUNTEAM.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('taille_texte', models.PositiveIntegerField(blank=True, null=True)),
                ('taille_barre', models.PositiveIntegerField(blank=True, null=True)),
                ('couleur', colorfield.fields.ColorField(default='#55d6aa', image_field=None, max_length=18, samples=None)),
                ('highlights', colorfield.fields.ColorField(default='#f54242', image_field=None, max_length=18, samples=None)),
            ],
        ),
    ]
