# Generated by Django 4.0.3 on 2022-06-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(blank=True, null=True)),
                ('img_upload', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('titre_slide', models.CharField(max_length=50)),
                ('taille_titre_slide1', models.PositiveIntegerField(blank=True, null=True)),
                ('texte_slide', models.TextField(max_length=2000)),
                ('taille_texte_slide', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(blank=True, null=True)),
                ('img_upload', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('generation', models.CharField(choices=[], max_length=100)),
                ('Nom', models.CharField(max_length=25)),
                ('description_perso', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('taille_titre', models.PositiveIntegerField(blank=True, null=True)),
                ('texte', models.TextField(max_length=4000)),
                ('taille_texte', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
