# Generated by Django 4.0.3 on 2022-06-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='generation',
            field=models.CharField(max_length=100),
        ),
    ]
